package h_exception

fun main() {

}